POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkR1Y2siLCJpZCI6IjYwNTI5NGRjZTkyNTY3NGY3NGNjYjQ0OSIsImlhdCI6MTYxNjAyNDgyN30.tAU8Imspctr-0vo7mae3abQ1pPshtne4mAUqup5_3Gc

{
    "content": "Isshiki",
    "important": true
}